[phases.setup]
nixPkgs = ['nodejs-18_x']

[phases.install]
cmds = [
  'npm ci',
  'cd client && npm ci && cd ..'
]

[phases.build]
cmds = [
  'cd client && npm run build && cd ..'
]

[start]
cmd = 'node server/server.js'